---
title: "Étude de l'obésité - Exploration"
author: "___"
date: "`r Sys.Date()`"
format:
  html:
    code-fold: true
    code-tools: true
    toc: true
editor: visual
lang: fr
---

```{r setup, include=FALSE}
SciViews::R(lang = "fr")
```

<!--# Cette balise est un commentaire.-->

<!--% Cette balise est une consigne.-->

<!--# Ce document est un carnet de notes. Il est par conséquent moins formel qu'un rapport. Vous pouvez structurer vos interprétations sous la forme de liste. -->

<!--% Le remplissage de ce document Quarto est totalement optionel et ne sera pas coté. Si vous avez du temps, vous pouvez déjà explorer les données et cela vous avancera pour le travail à réaliser durant le second quadrimestre. Sinon, laissez ce document tel quel. -->

# Exploration des données

<!-- Importez le tableau `biometry.rds` dans la variable `biometry`. -->

```{r import}

```

<!-- Pour chaque étudiant, réalisez un graphique et un tableau résumant les observations. Tous les tableaux et graphiques doivent être interprétés. Si un remaniement des données est nécessaire pour arriver au résultat, faites-le dans le même chunk en utilisant un autre nom pour le tableau modifié (ne modifez pas le tableau `biometry` original). -->

```{r plot1}

```

<!--% Interprétez le graphique ci-dessus en 1 à 3 phrases. -->

```{r tab1, warning=FALSE}

```

<!--% Interprétez le tableau ci-dessus en 1 à 3 phrases. -->

```{r plot2}

```

<!--% Interprétez le graphique ci-dessus en 1 à 3 phrases. -->

```{r tab2, warning=FALSE}

```

<!--% Interprétez le tableau ci-dessus en 1 à 3 phrases. -->

```{r plot3}

```

<!--% Interprétez le graphique ci-dessus en 1 à 3 phrases. -->

```{r tab3, warning=FALSE}

```

<!--% Interprétez le tableau ci-dessus en 1 à 3 phrases. -->

```{r plot4}

```

<!--% Interprétez le graphique ci-dessus en 1 à 3 phrases. -->

```{r tab4, warning=FALSE}

```

<!--% Interprétez le tableau ci-dessus en 1 à 3 phrases. -->

<!--% Si une équipe est constituée de cinq personnes, la dernière rempli les chunks suivants, sinon, vous pouvez les effacer du document. -->

```{r plot5}

```

<!--% Interprétez le graphique ci-dessus en 1 à 3 phrases. -->

```{r tab5, warning=FALSE}

```

<!--% Interprétez le tableau ci-dessus en 1 à 3 phrases. -->
